### ISSUE TITLE
Clarify what is a 'Standardization Target'

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-modspec#14]
Probably with, or maybe through, examples

**Comment by cnreediii** [comment]
Totally agree!

**Comment by cnreediii** [comment]
Short discussion during July 23 call. Agreement that examples would be very useful. Also, there was a discussion to help all of us understand the difference between a standardization target and a standardization target type. The feature type concept was used to help clarify. Carl added examples and more informative wording to T&Ds. 

https://github.com/opengeospatial/ogc-modspec/blob/cnreediii-patch-6/sources/sections/04-terms-and-defs.adoc
