### ISSUE TITLE
Odd sentence at (old) 7.2.2, about subpackages

### ISSUE THREAD

**Issue by PeterParslow** [opengeospatial/ogc-modspec#32]
08-131r3 Clause 7.2.2 bullet point 1 says:

"Packages can be contained in one another. A subpackage of a package A is either A or a packages contained in a subpackage of A. A leaf package is one that contains no subpackages other than itself, but does contain classifiers."

I have no idea what the middle sentence* is meant to mean; it may be better to leave it out. Or perhaps to replace it with "If necessary, a package can be considered to be a sub-package of itself" - although I can't think when that might be necessary!

*"A subpackage of a package A is either A or a packages contained in a subpackage of A"

If it serves some necessary purpose, do please at least align the plural/singular - not "a packages"!

**Comment by cnreediii** [comment]
@PeterParslow Interesting - I also found this sentence confusing but, as I am not a UML expert, did not propose any edits. I am proposing that the UML Model requirements class be moved to a separate Part. That way the "core" and any Parts can usually be revised and approved independently.
