### ISSUE TITLE
Use of concept "permission" in the ModSpec

### ISSUE THREAD

**Issue by cnreediii** [opengeospatial/ogc-modspec#34]
The OAB recommended adding words to the ModSpec stating that a permissions cannot override a requirement. Note by CR: Also need more informative wording for "permission" and also need to add "permission" to T&Ds.

**Comment by dr-shorthair** [comment]
This also needs to be aligned with the 'normative terms' definitions. 
i.e. https://www.rfc-editor.org/rfc/rfc2119 (IETF) or 
https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor078

**Comment by cnreediii** [comment]
Agreed. Reading the ISO directives, I think the use of "permission" in OGC standards is inconsistent (and perhaps also in the ModSpec!).

**Comment by cnreediii** [comment]
From August 23, 2024 meeting: Defer any final decision until a later date. First decision is whether "Permission" will be a concept in the ModSpec revision. If the answer is yes, then the recommendation is to use the IDO definition. Based on the conversation, if we keep the permission concept, then a permission must be associated with a requirement.
