### ISSUE TITLE
Split ModSpec document into "Core" and Parts

### ISSUE THREAD

**Issue by cnreediii** [opengeospatial/ogc-modspec#36]
During the July 23 concall, we discussed the idea of splitting the ModSpec into a Core document with Parts. This approach is consistent with many other OGC Standards. Looking at the requirements in the ModSpec we have:

Core - Requirements 1 - 27
Part - UML Model requirements 28 - 38
Part - XML Model requirements 39 - 44
Part - Schematron requirements 45 - 50
Part - XML Metaschema requirements 51 - 52

There was general agreement that this approach makes sense.

**Comment by cnreediii** [comment]
Rob- OWL is an on-gong requirement. A version of the ModSpec as an ontology to characterize relationships between things. SOSA, CRS ontology examples.
Frank - Similar point. Provision for modelling for linked data.
Simon - XML Schema part of XML

**Comment by cmheazel** [comment]
Regarding the parts, the XML Model, Schematron, and XML Meta-schema requirements are all specific to XML.  So they should all be grouped in the same part.

**Comment by cnreediii** [comment]
Recommendation: Split the current ModSpec into a Core and then additional Parts. UML and XML would for sure be additional parts. JSON would also then be an additional part.

Approved August 20, 2024

**Comment by cmheazel** [comment]
And OWL/RDF?

**Comment by cnreediii** [comment]
@cmheazel Yes - Issue 18 also.
