### ISSUE TITLE
The ModSpec is NOT an OGC Policy (extracted from old Issue 9)

### ISSUE THREAD

**Issue by cnreediii** [opengeospatial/ogc-modspec#37]
During the July 23rd call we discussed whether the OGC ModSpec is an OGC Policy document or not. After discussion, the consensus is that Version 2 should not be an OGC Policy document. That way, other SDOs can use and implement the ModSpec without OGC specific requirements. The second part of the agreement is that the OGC will develop a very short companion document that is an OGC Policy Directive - basically that the ModSpec is OGC Policy. Further, the short companion document will contain OGC specific requirements, such as every OGC standard shall have an ATS. The last point is related to an issue of whether specifying conformance classes is mandatory.

However, given that the ModSpec goes through the formal RFC approval process, the ModSpec is a normative OGC document and as such is a Standard - albeit a standard for writing standards.

**Comment by dr-shorthair** [comment]
ModSpec is also an ISO/TC 211 'policy'. 
Clemens and I wrote it up in 2011, was adopted by TC 211 around that time. 
The primary effect is that ISO 19100 standards since that time have URIs for all requirements, text, etc.

**Comment by cmheazel** [comment]
The ModSpec is cited by the NSG Registry.  While it's not explicitly called out as a Standard, it is often cited as one.  It is definitely NOT treated as a U.S. Government policy document.

**Comment by cnreediii** [comment]
Agreed to August 20. Also agreed that a short companion document will be written that does make the ModSPec a Policy for the development of OGC Standards.

**Comment by cnreediii** [comment]
Done!
