### ISSUE TITLE
Transfer ogc-modspec repository to OGC (GitHub: opengeospatial)

### ISSUE THREAD

**Issue by ronaldtse** [opengeospatial/ogc-modspec#7]
As per the recent discussion with the ModSpec revision, we are transferring this repository to OGC (@opengeospatial) officially so the document can be revised by the OAB.

This is as agreed with OGC's @ogcscotts.

Ping @gbuehler @ghobona

**Comment by ronaldtse** [comment]
@ogcscotts I can't do it since I don't have permissions at the OGC GitHub organization account.

However, I made you an "admin" in this repository, so you should be able to do it.

**Comment by ogcscotts** [comment]
Thanks, @ronaldtse , but please make @gbuehler the admin as he has the rights for OGC

**Comment by ronaldtse** [comment]
> Thanks, @ronaldtse , but please make @gbuehler the admin as he has the rights for OGC

Done. Ping @gbuehler .

**Comment by ronaldtse** [comment]
@ghobona is doing it now.

**Comment by cnreediii** [comment]
All good now!  Thanks all!
